{% set name = "pyflyde" %}
{% set version = "0.0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyflyde-{{ version }}.tar.gz
  sha256: da6e591d7fa54517d67d2368c596f1f9bd126f9d3d257bb57fa7d0f86e576911

build:
  entry_points:
    - pyflyde = flyde.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >=3.9
    - pyyaml

test:
  imports:
    - flyde
  commands:
    - pip check
    - pyflyde --help
  requires:
    - pip

about:
  summary: Python SDK and runtime for Flyde - a visual flow-based programming language and IDE.
  home: https://pyflyde.readthedocs.io
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
